import './style.css';
import { createCity } from './city.js';
import { generateSession, validateSession, validateFrame, frameAt } from './model.js';
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=generateSession(),time=0,playing=true,speed=1,selected='mm',lastSeq=-1,mode='replay',socket=null,lastReceived=0,log=[],city;
try{city=createCity($('world'),select);}catch(error){$('notice').textContent=`3D renderer unavailable: ${error.message}. Data panels remain available.`;city={update(){},emit(){},focus(){},home(){},clearEffects(){}};}
function select(id){selected=id;city.focus(id);renderInspector(current());}
function current(){return mode==='live'?session.frames.at(-1):frameAt(session.frames,time);}
function kv(key,value){return `<div class="kv"><span>${escape(key)}</span><b>${escape(value)}</b></div>`;}
function renderInspector(f){const s=f.strategies.find(s=>s.id===selected),feed=f.feeds.find(x=>x.id===selected);let html;
  if(s)html=`<h3>${escape(s.name)}</h3>`+[['Instrument',s.symbol],['Status',s.state],['P&L',money(s.pnl)],['Position',s.position],['Orders',s.orders],['Fills',s.fills],['Demo p99 (µs)',s.latency/1000]].map(x=>kv(...x)).join('');
  else if(feed)html=`<h3>Feed ${feed.id}</h3>`+[['Health',feed.state],['Packet sequence',feed.seq],['Observed gaps',feed.gaps]].map(x=>kv(...x)).join('');
  else html=`<h3>${escape(selected.toUpperCase())}</h3><p class="muted">Read-only visualization of simulated infrastructure. Order animations illustrate stages; their animation durations are not measured latencies.</p>`;
  const latest=log.find(e=>e.orderId&&(!s||e.strategyId===s.id));if(latest)html+='<h2 style="margin-top:20px">Latest observed order</h2>'+[['Order',latest.orderId],['Stage',latest.type],['Side',latest.side],['Quantity',latest.qty],['Price',latest.price]].map(x=>kv(...x)).join('');$('inspector').innerHTML=html;
}
function draw(f,animate=false){city.update(f);$('metrics').innerHTML=[['Session P&L',money(f.strategies.reduce((a,s)=>a+s.pnl,0))],['Filled orders',f.strategies.reduce((a,s)=>a+s.fills,0)],['Feed health',f.feeds.every(x=>x.state==='HEALTHY')?'HEALTHY':'DEGRADED'],['Source',mode==='live'?'DEMO WS':'DEMO REPLAY']].map(([k,v])=>`<div class="metric"><small>${k}</small><strong>${v}</strong></div>`).join('');
  $('strategies').innerHTML=[...f.strategies].sort((a,b)=>b.pnl-a.pnl).map(s=>`<button class="row" data-id="${s.id}"><span>${escape(s.name)}<small>${escape(s.symbol)} · ${s.state}</small></span><b class="${s.pnl>=0?'positive':'negative'}">${money(s.pnl)}</b></button>`).join('');
  $('feeds').innerHTML=f.feeds.map(x=>`<button class="row" data-id="${x.id}"><span>Feed ${x.id}<small>seq ${x.seq.toLocaleString()}</small></span><b class="${x.state==='HEALTHY'?'positive':'negative'}">${x.state}</b></button>`).join('');
  if(animate)f.events.forEach(e=>city.emit(e));renderInspector(f);$('events').innerHTML=log.slice(0,12).map(e=>`<div class="event"><b>${escape(e.type)}</b><br>${escape(e.orderId||`Feed ${e.feed}`)} · ${e.time.toFixed(3)}s</div>`).join('');$('clock').textContent=`${f.time.toFixed(1)}s`;if(mode!=='live')$('scrub').value=time;
}
function rebuildLog(t){log=session.frames.filter(f=>f.time<=t).flatMap(f=>f.events).slice(-60).reverse();}
function seek(t){time=t;lastSeq=frameAt(session.frames,t).seq;city.clearEffects();rebuildLog(t);draw(current());}
function setPlaying(value){playing=value;$('play').textContent=value?'Pause':'Play';}
function disconnect(){if(socket){socket.onclose=null;socket.close();socket=null;}mode='replay';$('connection').textContent='LOCAL SIMULATION';$('connect').textContent='Connect WS';$('scrub').disabled=false;$('play').disabled=false;$('speed').disabled=false;$('scrub').min=session.frames[0].time;$('scrub').max=session.frames.at(-1).time;}
function load(s){validateSession(s);disconnect();session=s;lastSeq=-1;$('scrub').min=s.frames[0].time;$('scrub').max=s.frames.at(-1).time;seek(s.frames[0].time);setPlaying(true);$('mode').textContent='REPLAY';}
$('strategies').onclick=$('feeds').onclick=e=>{const button=e.target.closest('[data-id]');if(button)select(button.dataset.id);};
$('home').onclick=()=>city.home();function toggleCinema(){document.body.classList.toggle('cinematic');$('cinematic').textContent=document.body.classList.contains('cinematic')?'Engineering':'Cinematic';}
$('cinematic').onclick=toggleCinema;document.addEventListener('keydown',e=>{if(e.key==='Tab'&&e.target===document.body){e.preventDefault();toggleCinema();}});
$('play').onclick=()=>{if(!playing&&time>=session.frames.at(-1).time)seek(session.frames[0].time);setPlaying(!playing);};$('speed').onchange=e=>speed=Number(e.target.value);$('scrub').oninput=e=>{setPlaying(false);seek(Number(e.target.value));};
$('demo').onclick=()=>load(generateSession());$('eod').onclick=()=>{disconnect();setPlaying(false);seek(session.frames.at(-1).time);$('mode').textContent='END OF DAY';};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(session)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='market-nexus-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>25*1024*1024)throw Error('Maximum session size is 25 MB');load(JSON.parse(await file.text()));$('notice').textContent='Replay imported. Values are displayed as supplied by the file.';}catch(err){$('notice').textContent=`Import failed: ${err.message}`;}e.target.value='';};
$('connect').onclick=()=>{if(mode==='live'){disconnect();load(generateSession());return;}const url=prompt('Read-only telemetry WebSocket URL','ws://127.0.0.1:8787');if(!url)return;try{const parsed=new URL(url);if(!['ws:','wss:'].includes(parsed.protocol))throw Error('Use ws:// or wss://');disconnect();const ws=new WebSocket(url);socket=ws;$('connection').textContent='CONNECTING';let liveSeq=-1,liveTime=-1;
  ws.onopen=()=>{const initial=current();mode='live';session={version:1,label:'Demo WebSocket capture',frames:[initial]};log=[];lastReceived=performance.now();$('connection').textContent='CONNECTED / DEMO WS';$('connect').textContent='Disconnect';$('scrub').disabled=true;$('play').disabled=true;$('speed').disabled=true;$('mode').textContent='LIVE VIEW';};
  ws.onmessage=e=>{try{if(typeof e.data!=='string'||e.data.length>128000)throw Error('Oversize or binary frame');const f=validateFrame(JSON.parse(e.data));if(f.seq<=liveSeq||f.time<=liveTime)throw Error('Out-of-order frame');if(liveSeq>=0&&f.seq!==liveSeq+1)$('notice').textContent='Sequence gap: fresh full-state frame applied; intervening event animations unavailable.';liveSeq=f.seq;liveTime=f.time;lastReceived=performance.now();if(session.frames[0]?.seq>=f.seq||session.frames[0]?.time>=f.time)session.frames=[];session.frames.push(f);if(session.frames.length>12000)session.frames.shift();log=[...f.events].reverse().concat(log).slice(0,60);draw(f,true);$('connection').textContent='CONNECTED / DEMO WS';}catch(err){$('notice').textContent=`Telemetry rejected: ${err.message}`;}};
  ws.onerror=()=>{$('notice').textContent='WebSocket connection failed. Start npm run server in a second terminal.';};ws.onclose=()=>{$('connection').textContent='DISCONNECTED / STALE';$('notice').textContent='Last received state is frozen. Reconnect or start a new demo session.';socket=null;};
}catch(err){$('notice').textContent=err.message;}};
let previous=performance.now();function tick(now){const dt=Math.min((now-previous)/1000,.25);previous=now;if(mode==='replay'&&playing){const start=time;time=Math.min(time+dt*speed,session.frames.at(-1).time);const f=current();if(f.seq!==lastSeq){const crossed=session.frames.filter(x=>x.time>start&&x.time<=time);for(const frame of crossed){log=[...frame.events].reverse().concat(log).slice(0,60);frame.events.forEach(e=>city.emit(e));}lastSeq=f.seq;draw(f);}if(time>=session.frames.at(-1).time)setPlaying(false);}else if(mode==='live'&&now-lastReceived>3000)$('connection').textContent='STALE / NO UPDATES';requestAnimationFrame(tick);}seek(0);requestAnimationFrame(tick);
